name: colendi_web_view_sdk_flutter
description: The Colendi Web View is a Software Development Kit developed by Colendians to enable fast and simple integration to Colendi World.
version: 1.2.3
homepage: https://github.com/colendi-project/ColendiWebViewSDK-Flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.6.0+2
  locale_plus: ^1.1.0
  url_launcher: ^6.0.18
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.colendi.colendi_web_view_sdk_flutter
        pluginClass: ColendiWebViewSdkFlutterPlugin
      ios:
        pluginClass: ColendiWebViewSdkFlutterPlugin